In [2]:
import pandas as pn
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sb

In [16]:
appMedico = pn.read_csv("C:/Users/VIVOBOOK/Downloads/start Notebook jupyter/appoinement medeco.csv", delimiter=";")

In [19]:
appMedico.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,"2,99E+13",5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,"5,59E+14",5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,"4,26E+12",5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,"8,68E+11",5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,"8,84E+12",5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [21]:
appMedico.info()

<class 'pandas.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  str
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  str
 3   ScheduledDay    110527 non-null  str
 4   AppointmentDay  110527 non-null  str
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  str
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  str
dtypes: int64(8), str(6)
memory usage: 11.8 MB

## after the call of the Dataset of appointment Medico We See
    - There two datatype on this file
    - also after call the header of the file there some columns take importance to the others like 
    [
        ScheduledDay,
        AppointmentDay,
        Age,
        Scholarship,
        Hipertension,
        Diabetes,
        Alcoholism,
        Handcap,
        SMS_received
    ]

In [50]:
# import ydata_profiling
# from ydata_profiling import ProfileReport

# import numpy as np
# #
# print(np.add([14, 58], [45, 101]))

In [51]:
# ProfileReport(appMedico, title="Appointments Medico Report")

In [53]:
appMedico.describe()

,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [64]:
# appMedico.hist(appMedico["Age"])
lenArr = len(appMedico['Age'])

print(lenArr)
print(appMedico['Age'])

# plt.hist(appMedico, bins=lenArr, color='skyblue', edgecolor='black')

# plt.title('Age Distribution')
# plt.xlabel("values")
# plt.ylabel('Frequency')

# plt.show()

110527
0         62
1         56
2         62
3          8
4         56
          ..
110522    56
110523    51
110524    21
110525    38
110526    54
Name: Age, Length: 110527, dtype: int64

In [66]:
# import matplotlib.pyplot as plt
# import numpy as np

# Generate random data for the histogram
data = np.random.randn(1000)

# Plotting a basic histogram
plt.hist(data, bins=30, color='skyblue', edgecolor='black')

# Adding labels and title
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Basic Histogram')

# Display the plot
plt.show()

ImportError: cannot import name 'backend_agg' from 'matplotlib.backends' (c:\Users\VIVOBOOK\Downloads\start Notebook jupyter\.venv\Lib\site-packages\matplotlib\backends\__init__.py)